                 List of relations
 Schema |          Name          | Type  |  Owner   
--------+------------------------+-------+----------
 public | agent_activity_log     | table | postgres
 public | agent_identities       | table | postgres
 public | agent_jobs             | table | postgres
 public | agent_workers          | table | postgres
 public | attachments            | table | postgres
 public | call_conversations     | table | postgres
 public | call_turns             | table | postgres
 public | chats                  | table | postgres
 public | collaborative_sessions | table | postgres
 public | conversation_sources   | table | postgres
 public | cross_references       | table | postgres
 public | cursor_positions       | table | postgres
 public | document_chunks        | table | postgres
 public | drafts                 | table | postgres
 public | edit_operations        | table | postgres
 public | entities               | table | postgres
 public | entity_mentions        | table | postgres
 public | evidence               | table | postgres
 public | execution_logs         | table | postgres
 public | executor_state         | table | postgres
 public | extracted_knowledge    | table | postgres
 public | feedback               | table | postgres
 public | google_oauth_tokens    | table | postgres
 public | ingestion_jobs         | table | postgres
 public | job_results            | table | postgres
 public | kernel_evolutions      | table | postgres
 public | kernels                | table | postgres
 public | knowledge_embeddings   | table | postgres
 public | llm_interactions       | table | postgres
 public | llm_usage              | table | postgres
 public | messages               | table | postgres
 public | queued_tasks           | table | postgres
 public | rag_chunk_lineage      | table | postgres
 public | rag_metrics_hourly     | table | postgres
 public | rag_retrieval_results  | table | postgres
 public | rag_traces             | table | postgres
 public | schedules              | table | postgres
 public | session_participants   | table | postgres
 public | sessions               | table | postgres
 public | sms_messages           | table | postgres
 public | ssh_hosts              | table | postgres
 public | ssh_keys               | table | postgres
 public | todo_items             | table | postgres
 public | tool_call_logs         | table | postgres
 public | tool_tasks             | table | postgres
 public | triggers               | table | postgres
 public | user_agents            | table | postgres
 public | user_branding          | table | postgres
 public | users                  | table | postgres
 public | voicemails             | table | postgres
 public | workflows              | table | postgres
(51 rows)

